# Generated by Django 3.1.2 on 2020-11-09 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_service_testsequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('cell_technology', models.CharField(max_length=50)),
                ('cell_manufacturer', models.CharField(max_length=50)),
                ('number_cells', models.IntegerField()),
                ('number_cells_series', models.IntegerField()),
                ('number_cells_strings', models.IntegerField()),
                ('number_diodes', models.IntegerField()),
                ('product_length', models.CharField(max_length=30)),
                ('product_width', models.CharField(max_length=30)),
                ('product_weight', models.CharField(max_length=30)),
                ('superstate_type', models.CharField(max_length=50)),
                ('superstate_manufacturer', models.CharField(max_length=50)),
                ('substrate_type', models.CharField(max_length=50)),
                ('substrate_manufacturer', models.CharField(max_length=50)),
                ('frame_type', models.CharField(max_length=50)),
                ('frame_adhesive', models.CharField(max_length=30)),
                ('encapsulate_type', models.CharField(max_length=30)),
                ('encapsulate_manufacturer', models.CharField(max_length=50)),
                ('junction_box_type', models.CharField(max_length=50)),
                ('junction_box_manufacturer', models.CharField(max_length=50)),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.certificate')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_voltage', models.IntegerField()),
                ('voc', models.CharField(max_length=20)),
                ('isc', models.CharField(max_length=20)),
                ('vmp', models.CharField(max_length=20)),
                ('imp', models.CharField(max_length=20)),
                ('pmp', models.CharField(max_length=20)),
                ('ff', models.CharField(max_length=20)),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('sequence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.testsequence')),
            ],
        ),
    ]
